config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  root to: 'pages#index'
  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  default_scope -> { includes(:user).order(created_at: :desc) }

  scope :by_category, -> (branch, category_name) do
    joins(:category).where(categories: {name: category_name, branch: branch})
  end

  scope :by_branch, -> (branch) do
    joins(:category).where(categories: {branch: branch})
  end

  scope :search, -> (search) do
    where("title ILIKE lower(?) OR content ILIKE lower(?)", "%#{search}%", "%#{search}%")
  end

  validates :title, presence: true, length: { minimum: 5, maximum: 255 }
  validates :content, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :category_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def redirect_if_not_signed_in
    redirect_to root_path if !user_signed_in?
  end

  def redirect_if_signed_in
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @hobby_posts = Post.by_branch('hobby').limit(8);
    @study_posts = Post.by_branch('study').limit(8);
    @team_posts = Post.by_branch('team').limit(8);
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_if_not_signed_in, only: [:new]
  def new
    @branch = params[:branch]
    @categories = Category.where(branch: @branch)
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      redirect_to root_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def hobby
    posts_for_branch(params[:action])
  end

  def study
    posts_for_branch(params[:action])
  end

  def team
    posts_for_branch(params[:action])
  end



  private

  def posts_for_branch(branch)
    respond_to |format|
      format.html
      format.js { render partial: 'posts/posts_pagination_page' }
    end
    @categories = Category.where(branch: branch)
    @posts = get_posts.paginate(page: params[:page])
  end

  def get_posts
    PostsForBranchService.new({
      search: params[:search],
      category: prams[:category],
      branch: params[:action]
      }).call
  end

  def post_params
    params.require(:post).permit(:content, :title, :category_id).merge(user_id: current_user.id)
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end


  def account_update_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'
module ApplicationHelper
  include NavigationHelper
  include PostsHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def create_new_post_partial_path
    if user_signed_in?
      'posts/branch/create_new_post/signed_in'
    else
      'posts/branch/create_new_post/not_signed_in'
    end
  end

  def all_categories_button_partial_path
    if params[:category].blank?
      'posts/branch/categories/all_selected'
    else
      'posts/branch/categories/all_not_selected'
    end
  end

  def no_posts_partial_path(posts)
    posts.empty? ? 'posts/shared/no_posts' : 'shared/empty_partial'
  end

  def post_format_partial_path
    current_page?(root_path) ? 'posts/post/home_page' : 'posts/post/branch_page'
  end

  def category_field_partial_path
    if params[:category].present?
      'posts/branch/search_form/category_field'
    else
      'shared/empty_partial'
    end
  end

  def update_pagination_partial_path
    if @posts.next_page
      'posts/posts_pagination_page/update_pagination'
    else
      'posts/posts_pagination_page/remove_pagination'
    end
  end


end

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- /.navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'Collabfield', root_path, class: 'navbar-brand' %>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li><%= link_to 'Login', login_path %></li>
<li><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>

  <li class="mobile-menu">
    <%= link_to 'Edit Profile', edit_user_registration_path %>
  </li>
  <li class="mobile-menu">
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  </li>

app/views/pages/shared/_empty_partial.html.erb
<div class="text-center">
  currently there are no published posts
</div>

app/views/posts/_branch.html.erb
<div id="branch-main-content" class="container">


  <div class="row">
    <h1 class="page-title"><%= page_title %></h1>
    <%= render 'posts/branch/create_new_post', branch: branch %>
  </div><!-- row -->

  <div class="row">
    <%= render 'posts/branch/search_form',
               branch: branch,
               search_placeholder: search_placeholder %>
  </div><!-- row -->

  <div class="row">
    <%= render 'posts/branch/categories', branch: branch %>
  </div>

  <div class="row">
    <div class="col-sm-12" id="feed">
      <%= render @posts %>
      <%= render no_posts_partial_path %>
    </div>
  </div><!-- row -->

  <div class="infinite-scroll">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/_modal.html.erb
<!-- Modal -->
<div class="modal myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="posted-by"></span>
        <button type="button" class="close" data-dismiss="modal" air-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="loaded-data">
          <h3></h3>
          <p></p>
          <div class="interested"><a href="">I'm interested</a></div>
        </div><!-- loaded-data -->
      </div><!-- modal-body -->
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<%= render post_format_partial_path, post: post %>

app/views/posts/_posts_pagination_page.js.erb
$('#feed').append('<%= j render @posts %>');
<%= render update_pagination_partial_path %>

app/views/posts/branch/_categories.html.erb
<% branch_path_name = "#{params[:action]}_posts_path" %>

<div class="col-sm-12">
  <ul class="categories-list">
    <%= render all_categories_button_partial_path,
    branch_path_name: branch_path_name %>
    <% @categories.each do |category| %>
      <li class="category-item">
        <%= link_to category.name,
                    send(branch_path_name,category: category.name),
                    :class => ("selected-item" if params[:category] == category.name) %>
      </li>
    <% end %>
  </ul>
</div><!-- col-sm-12 -->

app/views/posts/branch/_create_new_post.html.erb
<div class="col-sm-12">
  <div class="col-sm-8 col-sm-offset-2">
    <%= render create_new_post_partial_path, branch: branch %>
  </div><!-- col-sm-8 -->
</div><!-- col-sm-12 -->

app/views/posts/branch/_search_form.html.erb
<div class="col-sm-12">
  <%= form_tag(send("#{branch}_posts_path"),
               :method => "get",
               id: "search-form") do %>
    <i class="fa fa-search" aria-hidden="true"></i>
    <%= text_field_tag :search,
                       params[:search],
                       placeholder: search_placeholder,
                       class: "form-control" %>
    <%= render category_field_partial_path %>
  <% end %>
</div><!-- col-sm-12 -->

app/views/posts/branch/categories/_all_not_selected.html.erb
<li class="category-item">
  <%= link_to "All", send(branch_path_name) %>
</li>

app/views/posts/branch/categories/_all_selected.html.erb
<li class="category-item">
  <%= link_to "All",
              send(branch_path_name),
              :class => "selected-item" %>
</li>

app/views/posts/branch/create_new_post/_not_signed_in.html.erb
<div class="text-center login-branch">
  To create a new post you have to
  <%= link_to 'Login',
              login_path,
              class: 'login-button login-button-branch' %>
</div>

app/views/posts/branch/create_new_post/_signed_in.html.erb
<div class="new-post-button-parent">
  <span>Cannnot find anyone? Try to: </span>
  <%= link_to "Create a new post", new_post_path(branch: branch),
  :class => "new-post-button" %>
</div>

app/views/posts/hobby.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: {
  branch: 'hobby',
  page_title: 'Find a person with the same hobby',
  search_placeholder: 'E.g. guitar playing, programming, cooking'
} %>

app/views/posts/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a new post</h1>
      <%= render 'posts/new/post_form' %>
    </div>
  </div>
</div>

app/views/posts/post/_branch_page.html.erb
<div class="single-post-list" id=<%= post_path(post.id) %>>
  <%= truncate(post.title, :length => 60) %>
  <div class="post-content">
    <div class="posted-by">Posted by <%= post.user.name %></div>
    <h3><%= post.title %></h3>
    <p><%= post.content %></p>
    <%= link_to "I'm interested", post_path(post.id), class: 'interested' %>
  </div>
</div>

app/views/posts/post/_home_page.html.erb
<div class="col-sm-3 single-post-card" id=<%= post_path(post.id) %>>
  <div class="card">
    <div class="card-block">
      <h4 class="post-text">
        <%= truncate(post.title, :length => 60) %>
      </h4>
      <div class="post-content">
        <div class="posted-by">Posted by <%= post.user.name %></div>
        <h3><%= post.title %></h3>
        <p><%= post.content %></p>
        <%= link_to "I'm interested", post_path(post.id), class: 'interested' %>
      </div>
    </div>
  </div><!-- card -->
</div><!-- col-sm-3 -->

app/views/posts/posts_pagination_page/_remove_pagination.js.erb
$(window).off('scroll');
$('.pagination').remove();

app/views/posts/posts_pagination_page/_update_pagination.js.erb
$('.pagination').replacewith('<%= j will_paginate @posts %>');

app/views/posts/show.html.erb
<div class="container" id="single-post-content">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Posted by <%= @post.user.name %></div>
      <h3><%= @post.title %></h3>
      <p><%= @post.content %></p>
    </div>
  </div><!-- row -->
</div>

app/views/posts/stydy.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: {
  branch: 'stydy',
  page_title: 'Find a person whi stydies the same field as you',
  search_placeholder: 'E.g. nutrition, valculus, astrophysics'
} %>

app/views/posts/team.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: {
  branch: 'team',
  page_title: 'Find a person with similar interests as your team',
  search_placeholder: 'E.g. musitian for a band, developer for a project'
} %>

app/views/shared/_no_posts.html.erb
<div class="text-center">Currently there are no published posts</div>